# Generated by Django 3.2 on 2021-05-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('category', models.CharField(choices=[('Repairs', 'Ремонт'), ('Education', 'Образование'), ('Beauty and health', 'Красота и Здоровье'), ('Computers', 'Компьютеры'), ('Food', 'Еда')], max_length=32, verbose_name='Категория')),
                ('description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product_pics', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
