# Generated by Django 3.2 on 2021-05-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('can_no_moder_reviews', 'can_no_moder_reviews')], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
